---
deployment:
  tasks:
    - export DEPLOYPATH=home/diflniqt/public_html/wp-content/plugins/genesis-reservations
    - test -d "$(dirname $DEPLOYPATH)" || exit 1
    - mkdir -p $DEPLOYPATH
    - /bin/cp -R genesis-reservations.php assets $DEPLOYPATH/
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
